name: Build SimpleTweaksPlugin
on:
  push:
    branches: 'main'
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: [windows-2022]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.1
        with:
          vs-prerelease: true
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages [Release]
        if: "contains(github.event.head_commit.message, '[release]')"
        id: restoreNugetAttempt1Release
        continue-on-error: true
        run: nuget restore SimpleTweaksPlugin.sln

      - name: Restore NuGet Packages [Release] Attempt 2
        if: steps.restoreNugetAttempt1Release.outcome == 'failure'
        id: restoreNugetAttempt2Release
        continue-on-error: true
        run: nuget restore SimpleTweaksPlugin.sln

      - name: Restore NuGet Packages [Release] Attempt 3
        if: steps.restoreNugetAttempt2Release.outcome == 'failure'
        id: restoreNugetAttempt3Release
        run: nuget restore SimpleTweaksPlugin.sln
        
      - name: Restore NuGet Packages [Debug]
        if: "!contains(github.event.head_commit.message, '[release]')"
        id: restoreNugetAttempt1Debug
        continue-on-error: true
        run: nuget restore dev/SimpleTweaksPlugin.Dev.sln

      - name: Restore NuGet Packages [Debug] Attempt 2
        if: steps.restoreNugetAttempt1Debug.outcome == 'failure'
        id: restoreNugetAttempt2Debug
        continue-on-error: true
        run: nuget restore SimpleTweaksPlugin.sln

      - name: Restore NuGet Packages [Debug] Attempt 3
        if: steps.restoreNugetAttempt2Debug.outcome == 'failure'
        id: restoreNugetAttempt3Debug
        run: nuget restore SimpleTweaksPlugin.sln

#     - name: Download Dalamud
#       if: "!contains(github.event.head_commit.message, '[stg]')"
#       run: |
#         Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
#         Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Download Dalamud staging
#       if: "!contains(github.event.head_commit.message, '[stg]')"
        run: |
            Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
            Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
            
      - name: Build [Release]
        if: "contains(github.event.head_commit.message, '[release]')"
        run: msbuild SimpleTweaksPlugin.sln /p:Configuration=Release

      - name: Build [Debug]
        if: "!contains(github.event.head_commit.message, '[release]')"
        run: msbuild dev/SimpleTweaksPlugin.Dev.sln /p:Configuration=Debug

      - name: Extract [Release]
        if: "contains(github.event.head_commit.message, '[release]')"
        run: |
          Expand-Archive -Force ./bin/x64/Release/SimpleTweaksPlugin/latest.zip ./Artifact

      - name: Extract [Debug]
        if: "!contains(github.event.head_commit.message, '[release]')"
        run: |
          Expand-Archive -Force ./bin/x64/Debug/SimpleTweaksPlugin/latest.zip ./Artifact
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: ./Artifact/*